travis:
  secure:
    BINSTAR_TOKEN: t7jUfPM4h6GIJGZlJuWKijgYgaVO+vRL6wNfU9RzjfeYeuAlJWseXpyoWuLJJLunArSOlcf/HbgYNk8WoRto72bkJbeBxcBQCwQoS4vcrQPIk3Xc+IoHYVnY0THQoRmYTf1Bsa7rOay+khlEF2g/zczNQprc+OKvHPYHcroGQvAfqYunbq995L/0iljs3UqUHHbuOlje45CSSw8hfY7zCNVJQgyfHpnWqV7XU9mE/8VZtDbjYeMHPkiN6I03HpIY60hombNkR7KoqtSpy75x6iay/TLRCI++wtyd7HeDs39V1iGxK3sLszudbv5l4lUdB5YwfxMz0Aqd7LflgGJelKWG47T8RGMAmdtRVy+sNm9bPf6d2nLji56suxVOZWMV80gkSPf6Vs45EWWOEo52R0757B1chz3zz/lrhLeOFfR8vhWKHQTDBPs4CotJZ4X07bGliehGOVh/hCIzzO1mBFHhOZNmupafkKPBIBLU49jhGUD92pAZVXMHGsGsCnt0vF90Ybds2fJoEhx9bV77u3hpuXX7jO93pQ2fu37nYBhXveALQbYJ+56tvH7TodFankTpB+TP9JDOAqF6lPOp70pBcZxUK++v3fdZhwIZbDHmdv17ES6uvBboziK0ghLmcpFsQP/DuSNg01HAZjG3NtiarPhamv4JTTxeP5fDJwk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
